# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    com.taskie: DEBUG


server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091


swagger:
  # a comma separated string of the packages that contain your @Api annotated resources
  resourcePackage: com.taskie.resources,com.taskie.api

# Graphite metrics settings.
#metrics:
#  reporters:
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: taskie
#      frequency: 1m


# Taskie settings.
template: Hello, %s!
defaultName: Stranger


