logging:
  level: INFO
  loggers:
    com.taskie: DEBUG
server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
template: Hello, %s!
defaultName: Stranger
